#!/bin/bash

if [ "${RUN}" = "MOVE" ] 
then
    cd ${JENKINS_HOME} && mv * ${JENKINS_HOME_NEW}
    export JENKINS_HOME=${JENKINS_HOME_NEW}
fi

if [ -f ${JENKINS_HOME}/config.xml ] 
then
    java -jar /usr/share/jenkins/jenkins.war --httpPort=$PORT0 --logfile=${JENKINS_LOGFILE}
else
    sed -e "s,##JENKINS_MESOS_NAME##,${JENKINS_MESOS_NAME},g;s,##JENKINS_MESOS_MASTER##,${JENKINS_MESOS_MASTER},g;s,##JENKINS_MESOS_DESCRIPTION##,${JENKINS_MESOS_DESCRIPTION},g;s,##JENKINS_MESOS_FRAMEWORKNAME##,${JENKINS_MESOS_FRAMEWORKNAME},g;s,##JENKINS_MESOS_SLAVEUSER##,${JENKINS_MESOS_SLAVEUSER},g;s,##JENKINS_MESOS_PRINCIPAL##,${JENKINS_MESOS_PRINCIPAL},g;s,##JENKINS_MESOS_SECRET##,${JENKINS_MESOS_SECRET},g;s,##JENKINS_MESOS_ONDEMANDREGISTRATION##,${JENKINS_MESOS_ONDEMANDREGISTRATION},g;s,##JENKINS_MESOS_JENKINSURL##,${JENKINS_MESOS_JENKINSURL},g;s,##JENKINS_MESOS_SLAVE_LABEL##,${JENKINS_MESOS_SLAVE_LABEL},g" /config.xml > ${JENKINS_HOME}/config.xml && rm /config.xml
    java -jar /usr/share/jenkins/jenkins.war --httpPort=$PORT0 --logfile=${JENKINS_LOGFILE}
fi
